//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bolum()
        {
            this.Kisi = new HashSet<Kisi>();
        }
    
        public int BolumId { get; set; }
        public string BolumAdi { get; set; }
        public int FKFirmaId { get; set; }
        public string BolumKodu { get; set; }
        public byte[] BolumAcıklama { get; set; }
    
        public virtual Firma Firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kisi> Kisi { get; set; }
    }
}
