//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dersler()
        {
            this.EgitimSeans = new HashSet<EgitimSeans>();
        }
    
        public int DersId { get; set; }
        public int FKKategoriId { get; set; }
        public string DersAdi { get; set; }
        public string DersKodu { get; set; }
        public string Aciklama { get; set; }
        public int EgitimTuru { get; set; }
        public int FKEgitmenId { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EgitimSeans> EgitimSeans { get; set; }
        public virtual OnlineDers OnlineDers { get; set; }
        public virtual SinifIciDers SinifIciDers { get; set; }
        public virtual Egitmen Egitmen { get; set; }
    }
}
