//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firma()
        {
            this.Bolum = new HashSet<Bolum>();
            this.FirmaBankaBilgileri = new HashSet<FirmaBankaBilgileri>();
            this.Kisi = new HashSet<Kisi>();
        }
    
        public int FirmaId { get; set; }
        public string FirmaAdi { get; set; }
        public string Adres { get; set; }
        public string PostaKodu { get; set; }
        public int IlId { get; set; }
        public string Tel { get; set; }
        public string Cep { get; set; }
        public string Faks { get; set; }
        public string Mail { get; set; }
        public string FirmaImagePath { get; set; }
        public string FirmaKodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bolum> Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaBankaBilgileri> FirmaBankaBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kisi> Kisi { get; set; }
        public virtual Il Il { get; set; }
    }
}
