//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaBankaBilgileri
    {
        public int id { get; set; }
        public int FKFirma { get; set; }
        public string BankaAdi { get; set; }
        public string HesapNumarasi { get; set; }
    
        public virtual Firma Firma { get; set; }
    }
}
