//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiSeans
    {
        public int KisiSeansId { get; set; }
        public string KisiId { get; set; }
        public int EgitimSeansid { get; set; }
    
        public virtual EgitimSeans EgitimSeans { get; set; }
        public virtual Kisi Kisi { get; set; }
    }
}
