//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kisi()
        {
            this.KisiSeans = new HashSet<KisiSeans>();
        }
    
        public string KisiId { get; set; }
        public string KisiKimlikNo { get; set; }
        public string KisiAdi { get; set; }
        public string KisiSoyadi { get; set; }
        public System.DateTime KisiDogumTarihi { get; set; }
        public Nullable<int> KisiCinsiyet { get; set; }
        public string KisiEgitimSeviyesi { get; set; }
        public int IlId { get; set; }
        public int FKFirma { get; set; }
        public string KisiImagePath { get; set; }
        public Nullable<int> EhliyetSinifi { get; set; }
        public string EngelDurumu { get; set; }
        public string TelefonNo { get; set; }
        public int BolumId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Bolum Bolum { get; set; }
        public virtual Firma Firma { get; set; }
        public virtual Il Il { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KisiSeans> KisiSeans { get; set; }
    }
}
