//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineIcerik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineIcerik()
        {
            this.Sorular = new HashSet<Sorular>();
        }
    
        public int OnlineIcerikId { get; set; }
        public int OnlineId { get; set; }
        public int SoruSayisi { get; set; }
        public string CevapTipi { get; set; }
        public Nullable<int> BasarimOlcutu { get; set; }
    
        public virtual OnlineDers OnlineDers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorular> Sorular { get; set; }
    }
}
