//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineDers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineDers()
        {
            this.OnlineIcerik = new HashSet<OnlineIcerik>();
        }
    
        public int OnlineId { get; set; }
        public string OgrenimHedefleri { get; set; }
        public int Sure { get; set; }
        public string OrtamGereklilikleri { get; set; }
        public string Medya { get; set; }
        public Nullable<int> BasarimOlcutleri { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineIcerik> OnlineIcerik { get; set; }
    }
}
