//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinifIciDers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinifIciDers()
        {
            this.SinifIciIcerik = new HashSet<SinifIciIcerik>();
        }
    
        public int SinifIciId { get; set; }
        public string EgitimSorumlusu { get; set; }
        public string HedefKitle { get; set; }
        public int Seans { get; set; }
        public int SeansPeriyodu { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinifIciIcerik> SinifIciIcerik { get; set; }
    }
}
