//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinifIciIcerik
    {
        public int SinifIciIcerikId { get; set; }
        public int SinifIciId { get; set; }
        public string OgrenimHedefleri { get; set; }
        public int Sure { get; set; }
        public string OrtamGereklilikleri { get; set; }
        public string EgitmenMedya { get; set; }
    
        public virtual SinifIciDers SinifIciDers { get; set; }
    }
}
