//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        public int SoruId { get; set; }
        public int OnlineIcerikId { get; set; }
        public string Sorular1 { get; set; }
    
        public virtual CoktanSecmeliSorular CoktanSecmeliSorular { get; set; }
        public virtual DogruYanlisSorular DogruYanlisSorular { get; set; }
        public virtual OnlineIcerik OnlineIcerik { get; set; }
    }
}
